# $NetBSD: md.cats,v 1.56 2017/01/05 02:22:19 christos Exp $
./usr/X11R7/bin/X					xserver-x11-bin	xorg
./usr/X11R7/bin/Xorg					xserver-x11-bin	xorg
./usr/X11R7/bin/cvt					xserver-x11-bin	xorg
./usr/X11R7/bin/gtf					xserver-x11-bin	xorg
./usr/X11R7/bin/pcitweak				xserver-obsolete	obsolete
./usr/X11R7/bin/scanpci					xserver-obsolete	obsolete
./usr/X11R7/bin/xorgconfig				xserver-obsolete	obsolete
./usr/X11R7/lib/X11/Cards				xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.DRI			xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.fonts			xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.modes			xserver-x11-doc	xorg
./usr/X11R7/lib/X11/doc/README.rapidaccess		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/apm_drv.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/apm_drv.so		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/drivers/apm_drv.so.1		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/apm_drv.so.1		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/drivers/ark_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ark_drv.so.0		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ast_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ast_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ati_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ati_drv.so.6		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/chips_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/chips_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine.so	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine_drv.so	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_alpine_drv.so.1	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna.so	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna_drv.so	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_laguna_drv.so.1	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cyrix_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cyrix_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/glint_drv.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/glint_drv.so		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/drivers/glint_drv.so.1		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/glint_drv.so.1		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/drivers/i128_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/i128_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/i740_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/i740_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/imstt_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/imstt_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/kbd_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/kbd_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/mga_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/mga_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/mouse_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/mouse_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/neomagic_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/neomagic_drv.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/nsc_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/nsc_drv.so.2		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/nv_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/nv_drv.so.2		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/radeon_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/radeon_drv.so.6		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/radeonhd_drv.so		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/drivers/radeonhd_drv.so.1	xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/drivers/s3_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/s3_drv.so.0		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/s3virge_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/s3virge_drv.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/savage_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/savage_drv.so.2		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/siliconmotion_drv.so	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/siliconmotion_drv.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tdfx_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tdfx_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tga_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tga_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/trident_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/trident_drv.so.1	-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tseng_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/tseng_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/vesa_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/vesa_drv.so.2		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/vga_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/vga_drv.so.4		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/via_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/via_drv.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/void_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/void_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/ws_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/ws_drv.so.1		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/wsfb_drv.so		-unknown-	xorg
./usr/X11R7/lib/modules/drivers/wsfb_drv.so.0		-unknown-	xorg
./usr/X11R7/lib/modules/extensions/libcfb.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.so.0	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32_pic.a	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libdbe.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libdbe.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libdbe.so		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/libdbe.so.0		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libdbe.so.0		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/libdbe_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libdri.a		xserver-libdri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri.so		xserver-libdri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri.so.0		xserver-libdri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.a		xserver-libdri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.so		xserver-libdri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.so.0		xserver-libdri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libdri_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libextmod.so		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.so.0	-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libextmod.so.0	xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/libextmod_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libglx.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libglx.so		-unknown-	xorg
./usr/X11R7/lib/modules/extensions/libglx.so.0		-unknown-	xorg
./usr/X11R7/lib/modules/extensions/libglx_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libmfb.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/librecord.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/librecord.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/librecord.so		xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/librecord.so.0	-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/librecord.so.0	xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/extensions/librecord_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libshadow.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libshadow.so		-unknown-	xorg
./usr/X11R7/lib/modules/extensions/libshadow.so.0	-unknown-	xorg
./usr/X11R7/lib/modules/extensions/libshadow_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.so.0	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap_pic.a	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libexa.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libexa.so			-unknown-	xorg
./usr/X11R7/lib/modules/libexa.so.0			-unknown-	xorg
./usr/X11R7/lib/modules/libexa_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libfb.a				xserver-libfb-modules	xorg
./usr/X11R7/lib/modules/libfb.so			xserver-libfb-modules	xorg
./usr/X11R7/lib/modules/libfb.so.0			xserver-libfb-modules	xorg
./usr/X11R7/lib/modules/libfb_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libi2c.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c.so			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c.so.0			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libint10.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libshadowfb.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libshadowfb.so			-unknown-	xorg
./usr/X11R7/lib/modules/libshadowfb.so.0		-unknown-	xorg
./usr/X11R7/lib/modules/libshadowfb_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libvbe.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libvbe.so			-unknown-	xorg
./usr/X11R7/lib/modules/libvbe.so.0			-unknown-	xorg
./usr/X11R7/lib/modules/libvbe_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libvgahw.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libvgahw.so			-unknown-	xorg
./usr/X11R7/lib/modules/libvgahw.so.0			-unknown-	xorg
./usr/X11R7/lib/modules/libvgahw_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libxaa.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libxaa.so			xserver-libxaa-modules	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/libxaa.so			xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/libxaa.so.0			xserver-libxaa-modules	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/libxaa.so.0			xserver-obsolete	xorg,xorg_server_ver=118,obsolete
./usr/X11R7/lib/modules/libxaa_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libxf1bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp_pic.a		xserver-obsolete	obsolete
./usr/X11R7/man/cat1/Xorg.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat1/cvt.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat1/gtf.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat1/pcitweak.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat1/scanpci.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat1/xorgconfig.0			xserver-obsolete	obsolete
./usr/X11R7/man/cat4/apm.0				xserver-x11-catman	.cat,xorg,xorg_server_ver=110
./usr/X11R7/man/cat4/apm.0				xserver-obsolete	.cat,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/cat4/ati.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/chips.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/cirrus.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/cyrix.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/exa.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/glint.0				xserver-x11-catman	.cat,xorg,xorg_server_ver=110
./usr/X11R7/man/cat4/glint.0				xserver-obsolete	.cat,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/cat4/i128.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/i740.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/imstt.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/kbd.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/mga.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/mousedrv.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/neomagic.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/nsc.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/nv.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/radeon.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/radeonhd.0				xserver-obsolete	.cat,xorg,obsolete
./usr/X11R7/man/cat4/s3.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/s3virge.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/savage.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/siliconmotion.0			xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/tdfx.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/trident.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/tseng.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/vesa.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/vga.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/via.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/void.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/ws.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat4/wsfb.0				xserver-x11-catman	.cat,xorg
./usr/X11R7/man/cat5/xorg.conf.0			xserver-x11-catman	.cat,xorg
./usr/X11R7/man/html1/Xorg.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html1/cvt.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html1/gtf.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html1/pcitweak.html			xserver-obsolete	obsolete
./usr/X11R7/man/html1/scanpci.html			xserver-obsolete	obsolete
./usr/X11R7/man/html1/xorgconfig.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/apm.html				xserver-x11-htmlman	html,xorg,xorg_server_ver=110
./usr/X11R7/man/html4/apm.html				xserver-obsolete	html,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/html4/ati.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/chips.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/cirrus.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/cyrix.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/exa.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/glint.html			xserver-x11-htmlman	html,xorg,xorg_server_ver=110
./usr/X11R7/man/html4/glint.html			xserver-obsolete	html,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/html4/i128.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/i740.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/imstt.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/kbd.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/mga.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/mousedrv.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/neomagic.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/nsc.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/nv.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/radeon.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/radeonhd.html			xserver-obsolete	html,xorg,obsolete
./usr/X11R7/man/html4/s3.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/s3virge.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/savage.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/siliconmotion.html		xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/tdfx.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/trident.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/tseng.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/vesa.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/vga.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/via.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/void.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/ws.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html4/wsfb.html				xserver-x11-htmlman	html,xorg
./usr/X11R7/man/html5/xorg.conf.html			xserver-x11-htmlman	html,xorg
./usr/X11R7/man/man1/Xorg.1				xserver-x11-man	.man,xorg
./usr/X11R7/man/man1/cvt.1				xserver-x11-man	.man,xorg
./usr/X11R7/man/man1/gtf.1				xserver-x11-man	.man,xorg
./usr/X11R7/man/man1/pcitweak.1				xserver-obsolete	obsolete
./usr/X11R7/man/man1/scanpci.1				xserver-obsolete	obsolete
./usr/X11R7/man/man1/xorgconfig.1			xserver-obsolete	obsolete
./usr/X11R7/man/man4/apm.4				xserver-x11-man	.man,xorg,xorg_server_ver=110
./usr/X11R7/man/man4/apm.4				xserver-obsolete	.man,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/man4/ati.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/chips.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/cirrus.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/cyrix.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/exa.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/glint.4				xserver-x11-man	.man,xorg,xorg_server_ver=110
./usr/X11R7/man/man4/glint.4				xserver-obsolete	.man,xorg,xorg_server_ver=118,obsolete
./usr/X11R7/man/man4/i128.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/i740.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/imstt.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/kbd.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/mga.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/mousedrv.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/neomagic.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/nsc.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/nv.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/radeon.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/radeonhd.4				xserver-obsolete	.man,xorg,obsolete
./usr/X11R7/man/man4/s3.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/s3virge.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/savage.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/siliconmotion.4			xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/tdfx.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/trident.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/tseng.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/vesa.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/vga.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/via.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/void.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/ws.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man4/wsfb.4				xserver-x11-man	.man,xorg
./usr/X11R7/man/man5/xorg.conf.5			xserver-x11-man	.man,xorg
./usr/X11R7/share/aclocal/xorg-server.m4		xserver-x11-share	xorg
