#!/bin/sh
#
# find_obj_path -- compare obj

_bomb()
{
    printf "%s\\n" "$@"
    exit 1
}

[ $# = 0 ] && _bomb "$0 <list_filename>"

[ -f "$1" ] || _bomb "$1 not found"

OBJDIR="/zpool/obj"

while read -r line; do
    if printf "%s" "$line" | grep -q 'unknown'; then
        obj="$(printf "%s" "$line" | cut -f 1)"
        #find "$OBJDIR" -type d -name 'destdir.amd64' -prune -o -name "${obj##*/}" -type f -print -exit 1 && printf "---\\n"
        find "$OBJDIR" -type f -name "${obj##*/}" -print -exit 1 && printf "---\\n"
    else
        printf "---\\n"
    fi
done < "$1" | paste "$1" -
