#!/usr/bin/env python

import argparse
from os import path

parser = argparse.ArgumentParser()
parser.add_argument('set', type=str)
parser.add_argument('file', type=str)
args = parser.parse_args()

if not path.exists(args.file):
    raise FileNotFoundError(f'{args.file}: no such file or directory')

with open(args.file, mode='r', encoding='utf-8') as f:
    for line in f:
        if '\tobsolete' in line:
            print(line.replace('-unknown-', f'{args.set}-obsolete'), end='')
        else:
            print(line, end='')

exit(0)
