#!/bin/sh

_load_config()
{
    if [ -f "$CONFIG" ]; then
        . "$CONFIG"
    else
        _bomb "$CONFIG not found"
        exit 1
    fi
}

_usage()
{
    cat <<_usage_
Usage: $PROGNAME [--arch architecture] [--category category]
                  [--destdir destdir] [--machine machine] [--releasedir releasedir]
                  operation

 Operations:
    pkg                         Create packages.
    kern                        Create kernel package.
    clean                       Clean working directories.
    cleanpkg                    Clean package directories.

 Options:
    --arch                      Set machine_arch to architecture.
                                [Default: deduced from "machine"]
    --destdir                   Set destdir.
                                [Default: $OBJ/destdir.$machine]
    --machine                   Set machine type for MACHINE_ARCH.
                                [Default: result of \`uname -m\`]
    --releasedir                Set RELEASEDIR.
    -h | --help                 Show this message and exit.
_usage_
    exit 1
}

_getopt()
{
    # Example:
    #   --obj=/usr/obj
    #         ^^^^^^^^^
    #          take it
    #
    # In this example, returned "/usr/obj"
    expr "x$1" : "x[^=]*=\\(.*\\)"
}

_check_non_posix_commands()
{
    local non_posix="hostname mktemp pkg_create pkg_admin"

    for cmd in $non_posix; do
        _bomb_if_command_not_found "$cmd"
    done
}
