#!/bin/sh

_load_config()
{
    if [ -f "$CONFIG" ]; then
        . "$CONFIG"
    else
        _bomb "$CONFIG not found"
        exit 1
    fi
}

_usage()
{
    cat <<_usage_
Usage: $PROGNAME [-a architecture] [-c config] [-d destdir] [-m machine] [-r releasedir] operation

 Operations:
    pkg                         Create packages.
    kern                        Create kernel package.
    clean                       Clean working directories.
    cleanpkg                    Clean package directories.

 Options:
    -a                          Set machine_arch to architecture.
                                [Default: deduced from "machine"]
    -c                          Specify config path
    -d                          Set destdir.
                                [Default: $OBJ/destdir.$machine]
    -m                          Set machine type for MACHINE_ARCH.
                                [Default: result of \`uname -m\`]
    -r                          Set RELEASEDIR.
    -h                          Show this message and exit.
_usage_
    exit 1
}

_getopt()
{
    # Example:
    #   --obj=/usr/obj
    #         ^^^^^^^^^
    #          take it
    #
    # In this example, returned "/usr/obj"
    expr "x$1" : "x[^=]*=\\(.*\\)"
}

_check_release_number_could_resolve()
{
    if [ "X$RELEASE" = "X" ]; then
        _bomb "cannot resolve \$RELEASE"
    fi
}

_check_non_posix_commands()
{
    local non_posix="hostname mktemp pkg_create pkg_admin"

    for cmd in $non_posix; do
        _bomb_if_command_not_found "$cmd"
    done
}
