#!/bin/sh

_begin_logging()
{
    _logging "===> basepkg command: $COMMANDLINE"
    _logging "===> basepkg started: $(date)"
    _logging "===> NetBSD version:     $RELEASE"
    _logging "===> MACHINE:            $machine"
    _logging "===> MACHINE_ARCH:       $machine_arch"
    _logging "===> Build platform:     $OPSYS $OSVERSION $(uname -m)"
}

_logging()
{
    printf "%s\\n" "$@" | tee -a "$LOG"
}

_end_logging()
{
    _logging "===> basepkg ended:   $(date)"
    printf "===> Summary of log:\\n"
    sed -e "s/^===>/    /g" "$LOG"
    printf "===> .\\n"
    rm -f "$LOG"
}
