#!/bin/sh

: ${SRC:=/usr/src}
: ${OBJ:=/usr/obj}
: ${PKGSRC:=/usr/pkgsrc}
: ${PACKAGES:=./packages}
host="$(hostname)"
machine="$(uname -m)"
machine_arch="$(uname -p)"
opsys="$(uname)"
osversion="$(uname -r)"
pkgtoolversion=""
prog="${0##*/}"
rcsid='$NetBSD: make_basepkg.sh,v 0.01 2016/10/19 15:36:22 enomoto Exp $'
utcdate="$(env TZ=UTC LOCALE=C date '+%Y-%m-%d %H:%M')"
user="${USER:-root}"
sets="${OBJ}/releasedir/${machine}/binary/sets"

if [ -f ${PKGSRC}/pkgtools/pkg_install/files/lib/version.h ]; then
	pkgtoolversion="$(awk '/PKGTOOLS_VERSION/ {print $3}' \
	${PKGSRC}/pkgtools/pkg_install/files/lib/version.h)"
else
	pkgtoolversion="20160410"
fi

###################################################
# make_dirtree -- Output Commmand For pkg_create.
#                 Base Root Hierarchy Information.
#
# Argument: None.
###################################################
make_dirtree() {
	arch_file=""
	if [ $machine = "amd64" ]; then
		arch_file="$SRC/etc/mtree/NetBSD.dist.$machine_arch" # XXX Only, amd64
	fi
	cat $SRC/etc/mtree/NetBSD.dist.base $arch_file | mtree -C | sed 's/^\.\///g' | \
	awk '{print "@exec install -d -o root -g wheel -m "substr($5, 6) " "$1 }' 
}

###########################################
# extract_base -- Extract Base Binary Sets
#
# Argument: None.
###########################################
extract_base() {
	for i in base comp etc games kern-GENERIC man misc modules tests text
	do
		test -d ./work/$i || mkdir -p ./work/$i
		tar zxvf $sets/$i.tgz -C ./work/$i
	done
}

make_list(){
	for i in "$@"
	do
  	echo "making $i package contents list..."
		if [ ! -d ./work/list ]; then
			mkdir -p ./work/list
		fi	
		find work/$i -type f | grep -v "mtree" | \
  	grep -v "obsolete" | sed "s/^work\/$i\///g" > work/list/file.$i
	done
}

###################################################
# make_BUILD_INFO -- Output String For +BUILD_INFO
#
# Argument: Packages Name
###################################################
make_BUILD_INFO(){
	for i in "$@"
	do
  	echo "making $i package build infomation..."
		echo "OPSYS=$opsys" > ./work/$i/+BUILD_INFO
		echo "OS_VERSION=$osversion" >> ./work/$i/+BUILD_INFO
		echo "OBJECT_FMT=ELF" >> ./work/$i/+BUILD_INFO
		echo "MACHINE_ARCH=$machine_arch" >> ./work/$i/+BUILD_INFO
		echo "MACHINE_GNU_ARCH=${MACHINE_GNU_ARCH}" >> ./work/$i/+BUILD_INFO
		echo "PKGTOOLS_VERSION=$pkgtoolversion" >> ./work/$i/+BUILD_INFO
	done
}

#############################################
# make_COMMENT -- Output String For +COMMENT
#
# Argument: Packages Name
#############################################
make_COMMENT(){
	for i in "$@"
	do
  	echo "making $i package comment..."
		echo "System Package for $i" > ./work/$i/+COMMENT
	done
}

###############################################
# make_CONTENTS -- Output String For +CONTENTS
#
# Argument: Packages Name
###############################################
make_CONTENTS(){
	for i in "$@"
	do
  	echo "making $i package contents from list..."
		echo "@name $i-`sh ${SRC}/sys/conf/osrelease.sh`" > work/$i/+CONTENTS
		echo "@comment Packaged at ${utcdate} UTC by ${user}@${host}" \
		>> ./work/$i/+CONTENTS
		echo "@comment Packaged using ${prog} ${rcsid}" >> ./work/$i/+CONTENTS
		echo "@cwd /" >> ./work/$i/+CONTENTS
		cat ./work/list/file.$i | grep -v '+[A-Z]' >> ./work/$i/+CONTENTS
	done
}

#######################################
# make_DESC -- Output String For +DESC
#
# Argument: Packages Name
#######################################
make_DESC(){
	for i in "$@"
	do
  	echo "making $i package description..."
		echo "NetBSD base system" > work/$i/+DESC
		echo "" >> work/$i/+DESC
		echo "Homepage:" >> work/$i/+DESC
		echo "http://www.netbsd.org/" >> work/$i/+DESC
	done
}

#####################################
# make_PKG -- Create Package Tarball
#
# Argument: Packages Name
#####################################
make_PKG(){
	for i in "$@"
	do
  	echo "making $i package using pkg_create..."
		pkg_create -l -U -B work/$i/+BUILD_INFO -c work/$i/+COMMENT \
		-d work/$i/+DESC -f work/$i/+CONTENTS -I / -p ${PWD}/work/$i work/$i 
  	mv work/$i.tgz ./${PACKAGES}/$i.tgz
	done
}

######################################################
# clean_plus_file -- Remove Packages Information File
#
# Argument: None.
######################################################
clean_plus_file(){
	find ./sets -name '\+[A-Z]*' | xargs rm -f
}

