#!/usr/bin/env sh

PKG_INSTALL_PREFIX="/usr/pkg"
PKG_DB="/var/db/basepkg"
PKG_ADD=${PKG_INSTALL_PREFIX}/sbin/pkg_add
PKG_ADMIN=${PKG_INSTALL_PREFIX}/sbin/pkg_admin
PKG_DELETE=${PKG_INSTALL_PREFIX}/sbin/pkg_delete
PKG_INFO=${PKG_INSTALL_PREFIX}/sbin/pkg_info
OPTIONS="-K ${PKG_DB}"
progname=${0##*/}

if [ $# != 1 ]; then
	cat << _usage_
Usage: ${progname} package
_usage_
fi

case "${progname}" in
	bpkg_add)
		${PKG_ADD} ${OPTIONS} $1
		;;
	bpkg_admin)
		${PKG_ADMIN} ${OPTIONS} $1
		;;
	bpkg_delete)
		${PKG_DELETE} ${OPTIONS} $1
		;;
	bpkg_info)
		${PKG_INFO} ${OPTIONS} $1
		;;
	*)
		exit 1
		;;
esac
