.Dd January 11, 2020
.Dt BASEPKG 1
.Os
.Sh NAME
.Nm basepkg
.Nd Experimental framework for NetBSD base system packaging
.Sh DESCRIPTION
.Nm
is framework of NetBSD base system packaging.
It consists of some shellscript and many database.
.Pp
There is prior art "syspkg" in NetBSD official source tree.
.Sh AUTHORS
.Bl -tag -width indent -compact
.It "Yuuki Enomoto"
Initial work
.El
.Sh BUG REPORT
Please send bug reports to
.Ar uki@e-yuuki.org
or GitHub issues
.Ar https://github.com/user340/basepkg/issues
.Sh PULL REQUESTS
We welcome pull requests to
.Ar https://github.com/user340/basepkg/pulls
.Sh SEE ALSO
basepkg.sh(1)
.Pp
Official Repository:
.Ar https://github.com/user340/basepkg
