#!/bin/sh

SELF="$0"
PKGNAME="$1"
STAGE="$2"
shift
shift

CURDIR=`pwd`
PKG_METADATA_DIR="${2-${CURDIR}}"
: ${PKGNAME=${PKG_METADATA_DIR##*/}}
: ${PKG_DBDIR=${PKG_METADATA_DIR%/*}}
: ${PKG_REFCOUNT_DBDIR=${PKG_DBDIR}.refcount}
PKG_REFCOUNT_FILES_DBDIR="${PKG_REFCOUNT_DBDIR}/files"
: ${PKG_PREFIX=@PREFIX@}

case ${STAGE} in
POST-INSTALL)
	sed -n "/^\# FILE: /{s/^\# FILE: //;p;}" ${SELF} | sort -u |
	while read file f_flags f_eg f_mode f_user f_group; do
		case ${file} in
			"") confinue ;;
			[!/]*) file="${PKG_PREFIX}/${file}" ;;
		esac
		case ${f_flags} in
			*c*) ;;
			*) continue;;
		esac
		case ${f_eg} in
			"") continue ;;
			[!/]*) f_eg="${PKG_PREFIX}/${f_eg}"
		esac

		shadow_dir="${PKG_REFCOUNT_FILES_DBDIR}${file}"
		perms="${shadow_dir}/+PERMISSIONS"
		preexist="${shadow_dir}/+PREEXISTING"
		token="${shadow_dir}/${PKGNAME}"
		if [ ! -d "${shadow_dir}" ]; then
			mkdir ${shadow_dir}
			if [ -f "${file}" ]; then
				echo "${PKGNAME}" > ${preexist}
			fi
		fi
		if test -f "$token" && \
		grep "^${PKG_METADATA_DIR}$" ${token} > /dev/null; then
			:
		else
			echo "${PKG_METADATA_DIR}" >> ${token}
		fi

		case ${f_mode}${$f_user}${f_group} in
			"") ;;
			* ) echo "${f_mode} ${f_user} ${f_group}" > perms ;;
		esac
		if [ ! -f "${file}" -a ! -f "${f_eg}" -a ! -c "${f_eg}" ]; then
			:
		else
			case "${f_flags}:${_PKG_CONFIG}:${_PKG_RCD_SCRIPTS}" in
			*f*:*:*|[!r]:yes:*|[!r][!r]:yes:*|[!r][!r][!r]:yes:*|*r*:yes:yes)
				if [ -f "${file}" ]; then
					echo "${PKGNAME}: ${file} already exists"
				elif [ -f "${f_eg}" -o -c "${f_eg}" ]; then
					echo "${PKGNAME}: copying ${f_eg} to ${file}"
				fi
			esac
		fi
	done
	;;
esac

exit 0
